import { lemonSqueezySetup, getSubscription } from '@lemonsqueezy/lemonsqueezy.js';
import { createClient } from '@supabase/supabase-js';

const supabaseAdmin = createClient(
  process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || 'http://localhost:54321',
  process.env.SUPABASE_SERVICE_ROLE_KEY || 'anon-key-placeholder'
);

lemonSqueezySetup({ apiKey: process.env.LEMON_SQUEEZY_API_KEY });

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const token = req.headers.authorization?.replace('Bearer ', '');
  if (!token) return res.status(401).json({ error: 'Unauthorized' });

  const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(token);
  if (authError || !user) return res.status(401).json({ error: 'Unauthorized' });

  const { data: profile } = await supabaseAdmin
    .from('profiles')
    .select('*')
    .eq('id', user.id)
    .single();

  const subId = profile?.stripe_subscription_id; 
  if (!subId) return res.status(400).json({ error: 'No subscription found' });

  try {
    const sub = await getSubscription(subId);
    if (sub.error) throw new Error(sub.error.message);
    const url = sub.data?.data?.attributes?.urls?.customer_portal;
    if (!url) {
      console.error('[Portal Error] No URL returned for subId:', subId, sub.data);
      throw new Error('Customer portal URL not generated by Lemon Squeezy');
    }
    res.status(200).json({ url });
  } catch (error) {
    console.error('Portal error:', error.message || error);
    res.status(500).json({ error: error.message || 'Unable to open billing portal' });
  }
}
